List<Map<String, dynamic>> mandapam = [
  {
    "imagePath": "assets/venue_images/v1.jpg",
    "venueName": "Grand Palace",
    "location": "Chennai",
    "rentPerDay": 15000,
    "rating": "4.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v2.jpg",
    "venueName": "Royal Convention Center",
    "location": "Bangalore",
    "rentPerDay": 18000,
    "rating": "5.0⭐",
    "guests": "500",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v3.jpg",
    "venueName": "Ocean View Hall",
    "location": "Goa",
    "rentPerDay": 22000,
    "rating": "3.5⭐",
    "guests": "250",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v4.jpg",
    "venueName": "Heritage Mahal",
    "location": "Hyderabad",
    "rentPerDay": 20000,
    "rating": "3.5⭐",
    "guests": "400",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v5.jpg",
    "venueName": "Sunset Banquet",
    "location": "Mumbai",
    "rentPerDay": 25000,
    "rating": "4.1⭐",
    "guests": "1000",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v1.jpg",
    "venueName": "Lotus Wedding Hall",
    "location": "Delhi",
    "rentPerDay": 17000,
    "rating": "4.3⭐",
    "guests": "225",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v2.jpg",
    "venueName": "Dreams Banquet",
    "location": "Kolkata",
    "rentPerDay": 16000,
    "rating": "4.0⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v3.jpg",
    "venueName": "Green Meadows",
    "location": "Pune",
    "rentPerDay": 19000,
    "rating": "5.0⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v4.jpg",
    "venueName": "Riverfront Hall",
    "location": "Ahmedabad",
    "rentPerDay": 14000,
    "rating": "3.9⭐",
    "guests": "300",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v5.jpg",
    "venueName": "Paradise Resort",
    "location": "Jaipur",
    "rentPerDay": 21000,
    "rating": "2.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v1.jpg",
    "venueName": "Star Banquet",
    "location": "Lucknow",
    "rentPerDay": 13000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v2.jpg",
    "venueName": "Skyline Convention",
    "location": "Kochi",
    "rentPerDay": 24000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v3.jpg",
    "venueName": "Regal Hall",
    "location": "Coimbatore",
    "rentPerDay": 15000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v4.jpg",
    "venueName": "Garden View",
    "location": "Trivandrum",
    "rentPerDay": 17500,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v5.jpg",
    "venueName": "Pearl Palace",
    "location": "Madurai",
    "rentPerDay": 16000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v1.jpg",
    "venueName": "Elite Banquet",
    "location": "Nagpur",
    "rentPerDay": 14500,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v2.jpg",
    "venueName": "Crown Plaza",
    "location": "Visakhapatnam",
    "rentPerDay": 20000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v3.jpg",
    "venueName": "Golden Hall",
    "location": "Patna",
    "rentPerDay": 12000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": true,
  },
  {
    "imagePath": "assets/venue_images/v4.jpg",
    "venueName": "Diamond Banquet",
    "location": "Indore",
    "rentPerDay": 17000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": false,
  },
  {
    "imagePath": "assets/venue_images/v5.jpg",
    "venueName": "Silver Palace",
    "location": "Mysore",
    "rentPerDay": 15000,
    "rating": "3.5⭐",
    "guests": "300",
    "isBooked": true,
  },
];
