final List<String> eventsLists = [
  "Select one",
  "Other Event"
  "Wedding",
  "Engagement",
  "Reception",
  "Mehndi Ceremony",
  "Sangeet Night",
  "Baby Shower",
  "Naming Ceremony",
  "Birthday Party",
  "Farewell Party",
  "Housewarming",
  "Anniversary Celebration",
  "Retirement Party",
  "Graduation Ceremony",
  "Corporate Event",
  "Team Outing",
  "Conference",
  "Seminar",
  "Workshop",
  "Product Launch",
  "Award Ceremony",
  "Exhibition",
  "Trade Fair",
  "Music Concert",
  "Dance Performance",
  "Fashion Show",
  "Sports Event",
  "Charity Event",
  "Fundraising Gala",
  "Festival Celebration",
  "Cultural Fest",
  "College Fest",
  "School Annual Day",
  "New Year Party",
  "Christmas Celebration",
  "Diwali Party",
  "Holi Celebration",
  "Eid Gathering",
  "Pongal Celebration",
  "Navratri Dandiya Night",
  "Halloween Party",
  "Valentine Day Event",
  "Friendship Day Celebration",
  "Community Gathering",
  "Family Reunion",
  "Kitty Party",
  "Bridal Shower",
  "Bachelor Party",
  "Bachelorette Party",
  "Get-Together",
  "Club Night",
];
