import 'venue.dart';

List<Venue> venueList = [
  Venue(
    id: 1,
    name: "Grand Palace Banquet",
    image: "assets/venue_images/v1.jpg",
    location: "Madurai, Tamil Nadu",
    price: "₹50,000/day",
    capacity: "500 guests",
    rating: 4.8,
    category: "Banquet",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 2,
    name: "Elite Conference Hall",
    image: "assets/venue_images/v2.jpg",
    location: "Coimbatore, Tamil Nadu",
    price: "₹15,000/day",
    capacity: "100 guests",
    rating: 4.5,
    category: "Conference",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 3,
    name: "Royal Garden Lawn",
    image: "assets/venue_images/v3.jpg",
    location: "Madurai, Tamil Nadu",
    price: "₹35,000/day",
    capacity: "700 guests",
    rating: 4.6,
    category: "Lawn",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 4,
    name: "Skyline Rooftop Venue",
    image: "assets/venue_images/v4.jpg",
    location: "Chennai, Tamil Nadu",
    price: "₹25,000/day",
    capacity: "150 guests",
    rating: 4.4,
    category: "Rooftop",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 5,
    name: "Sunset Beach Resort",
    image: "assets/venue_images/v5.jpg",
    location: "Pondicherry",
    price: "₹80,000/day",
    capacity: "300 guests",
    rating: 4.9,
    category: "Resort",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 6,
    name: "Green Valley Farmhouse",
    image: "assets/venue_images/v1.jpg",
    location: "Madurai, Tamil Nadu",
    price: "₹40,000/day",
    capacity: "400 guests",
    rating: 4.7,
    category: "Farmhouse",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 7,
    name: "Golden Crown Party Hall",
    image: "assets/venue_images/v3.jpg",
    location: "Erode, Tamil Nadu",
    price: "₹20,000/day",
    capacity: "200 guests",
    rating: 4.3,
    category: "Party Hall",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 8,
    name: "The Majestic Banquet",
    image: "assets/venue_images/v2.jpg",
    location: "Madurai, Tamil Nadu",
    price: "₹55,000/day",
    capacity: "600 guests",
    rating: 4.8,
    category: "Banquet",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 9,
    name: "Silver Springs Resort",
    image: "assets/venue_images/v5.jpg",
    location: "Ooty, Tamil Nadu",
    price: "₹90,000/day",
    capacity: "250 guests",
    rating: 4.9,
    category: "Resort",
    caticon: "assets/pngimages/1.png",
  ),
  Venue(
    id: 10,
    name: "Urban Conference Center",
    image: "assets/venue_images/v4.jpg",
    location: "Madurai, Tamil Nadu",
    price: "₹18,000/day",
    capacity: "120 guests",
    rating: 4.5,
    category: "Conference",
    caticon: "assets/pngimages/1.png",
  ),
  // Add remaining 10 similarly...
];
