// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4gpryZZafXL5__mACBuuDnf_3U3L-zE',
    appId: '1:799874652691:web:bc0cf3effcfe23d193fde6',
    messagingSenderId: '799874652691',
    projectId: 'commanuser-49372',
    authDomain: 'commanuser-49372.firebaseapp.com',
    storageBucket: 'commanuser-49372.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5V9rfH_SaXm6hHBChdFO0DOp2xuLqtuY',
    appId: '1:799874652691:android:3f3dbb702693764493fde6',
    messagingSenderId: '799874652691',
    projectId: 'commanuser-49372',
    storageBucket: 'commanuser-49372.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfAfHgEbWomgeioyH16mQ8XicMzeqaLuQ',
    appId: '1:799874652691:ios:e14cb66c6a02994593fde6',
    messagingSenderId: '799874652691',
    projectId: 'commanuser-49372',
    storageBucket: 'commanuser-49372.firebasestorage.app',
    iosBundleId: 'com.example.commonUser',
  );
}
