// import 'package:crackers/genz_crackers/model/product_model.dart';

// List<ProductCategory> productcategories = [
//   ProductCategory(
//     id: 1,
//     name: "Single Sound Crackers",
//     image: "assets/imgi_10_5.jpg",
//     products: [
//       Product(
//         id: 1,
//         name: "2 3/4\" Kurvi",
//         image: "assets/imgi_10_5.jpg",
//         size: "5 PCS",
//         price: 70,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 2,
//         name: "3 1/2\" Lakshmi",
//         image: "assets/imgi_11_7.jpg",
//         size: "5 PCS",
//         price: 150,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 3,
//         name: "4 Lakshmi",
//         image: "assets/imgi_11_7.jpg",
//         size: "5 PCS",
//         price: 200,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 4,
//         name: "Deluxe Lakshmi",
//         image: "assets/imgi_12_8.jpg",
//         size: "5 PCS",
//         price: 300,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 5,
//         name: "Gold Lakshmi",
//         image: "assets/imgi_13_165.jpg",
//         size: "5 PCS",
//         price: 300,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 6,
//         name: "5\" Lakshmi/Spider",
//         image: "assets/imgi_14_166.jpg",
//         size: "5 PCS",
//         price: 400,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 7,
//         name: "6\" Lakshmi/Jallikattu",
//         image: "assets/1000003267.jpg",
//         size: "5 PCS",
//         price: 500,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 8,
//         name: "1/4 Kg Adiyal",
//         image: "assets/imgi_15_9.jpg",
//         size: "1 PCE",
//         price: 250,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 9,
//         name: "1/2 Kg Adiyal",
//         image: "assets/imgi_16_10.jpg",
//         size: "1 PCE",
//         price: 500,
//         unit: "1 PKT",
//       ),
//       Product(
//         id: 10,
//         name: "1 Kg Adiyal",
//         image: "assets/imgi_17_11.jpg",
//         size: "1 PCE",
//         price: 1000,
//         unit: "1 PKT",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 2,
//     name: "Garland",
//     image: "assets/5000-walas-crackers-500x500.webp",
//     products: [
//       Product(
//         id: 11,
//         name: "1K Digital",
//         image: "assets/imgi_19_17.jpg",
//         size: "1 STRING",
//         price: 2000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 12,
//         name: "2K Digital",
//         image: "assets/imgi_20_18.jpg",
//         size: "1 STRING",
//         price: 4000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 13,
//         name: "5K Digital",
//         image: "assets/imgi_21_19.jpg",
//         size: "1 STRING",
//         price: 10000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 14,
//         name: "Mega Deluxe Special 50",
//         image: "assets/50-Deluxe-Cracker.webp",
//         size: "1 STRING",
//         price: 1700,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 15,
//         name: "Mega Deluxe Special 100",
//         image: "assets/50-Deluxe-Cracker.webp",
//         size: "1 STRING",
//         price: 3400,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 3,
//     name: "Bijili - Loose Crackers",
//     image: "assets/imgi_22_20.jpg",
//     products: [
//       Product(
//         id: 16,
//         name: "Red Bijili 50",
//         image: "assets/imgi_22_20.jpg",
//         size: "1 PKT",
//         price: 200,
//         unit: "1 BAG",
//       ),
//       Product(
//         id: 17,
//         name: "Red Bijili 100",
//         image: "assets/imgi_23_21.jpg",
//         size: "1 PKT",
//         price: 300,
//         unit: "1 BAG",
//       ),
//       Product(
//         id: 18,
//         name: "Stripped Bijili 100",
//         image: "assets/imgi_23_21.jpg",
//         size: "1 PKT",
//         price: 400,
//         unit: "1 BAG",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 4,
//     name: "Atom Bomb",
//     image: "assets/imgi_25_24.jpg",
//     products: [
//       Product(
//         id: 19,
//         name: "Hydro Bomb",
//         image: "assets/imgi_24_23.jpg",
//         size: "10 PCS",
//         price: 550,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 20,
//         name: "Classic Green 5 Ply",
//         image: "assets/imgi_25_24.jpg",
//         size: "10 PCS",
//         price: 1300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 21,
//         name: "Jurassic Bomb Special",
//         image: "assets/imgi_26_169.jpg",
//         size: "10 PCS",
//         price: 2000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 22,
//         name: "Animal Bomb 7 Ply",
//         image: "assets/ef0c0b158e54ad1c59dcabae1ca5ad2e.webp",
//         size: "10 PCS",
//         price: 2100,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 5,
//     name: "Twinkling Star",
//     image: "assets/45cm_Twinkling_Star_Crackersshope.com_.jpg",
//     products: [
//       Product(
//         id: 23,
//         name: "Twinkling Star 1 Feet",
//         image: "assets/imgi_43_39.jpg",
//         size: "10 PCS",
//         price: 250,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 24,
//         name: "Twinkling Star 4 Feet",
//         image: "assets/imgi_44_40.jpg",
//         size: "10 PCS",
//         price: 700,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 6,
//     name: "Ground Chakkar",
//     image: "assets/Ground Chakkar Big 25Pcs.jpg.webp",
//     products: [
//       Product(
//         id: 25,
//         name: "Chakkar Big",
//         image: "assets/imgi_34_34.jpg",
//         size: "10 PCS",
//         price: 370,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 26,
//         name: "Chakkar Special",
//         image: "assets/imgi_35_35.jpg",
//         size: "10 PCS",
//         price: 810,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 27,
//         name: "Chakkar Deluxe",
//         image: "assets/imgi_36_36.jpg",
//         size: "10 PCS",
//         price: 1550,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 28,
//         name: "Digital Wheel Big",
//         image: "assets/imgi_34_34.jpg",
//         size: "10 PCS",
//         price: 550,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 29,
//         name: "Digital Wheel Ashoka",
//         image: "assets/imgi_37_161.jpg",
//         size: "10 PCS",
//         price: 900,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 30,
//         name: "Digital Wheel Special",
//         image: "assets/imgi_38_162.jpg",
//         size: "10 PCS",
//         price: 1300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 31,
//         name: "Digital Wheel Deluxe",
//         image: "assets/imgi_39_163.jpg",
//         size: "10 PCS",
//         price: 2300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 32,
//         name: "Ring Ring Wheel",
//         image: "assets/imgi_40_37.jpg",
//         size: "5 PCS",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 33,
//         name: "Hot Wheel",
//         image: "assets/imgi_42_38.jpg",
//         size: "5 PCS",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 34,
//         name: "Whistling Wheel",
//         image: "assets/imgi_41_132.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 7,
//     name: "Flower Pots",
//     image: "assets/DSC0063-scaled.jpg",
//     products: [
//       Product(
//         id: 35,
//         name: "Flower Pots Big",
//         image: "assets/imgi_27_27.jpg",
//         size: "10 PCS",
//         price: 600,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 36,
//         name: "Flower Pots Special",
//         image: "assets/imgi_28_28.jpg",
//         size: "10 PCS",
//         price: 900,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 37,
//         name: "Flower Pots Ashoka",
//         image: "assets/imgi_29_29.jpg",
//         size: "10 PCS",
//         price: 1100,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 38,
//         name: "Colour Koti XL",
//         image: "assets/imgi_30_31.jpg",
//         size: "10 PCS",
//         price: 1950,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 39,
//         name: "Colour Koti Red & Green Balls",
//         image: "assets/imgi_33_167.jpg",
//         size: "5 PCS",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 40,
//         name: "Colour Koti Deluxe Special",
//         image: "assets/imgi_31_32.jpg",
//         size: "10 PCS",
//         price: 2850,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 41,
//         name: "Splatoon",
//         image: "assets/imgi_32_33.jpg",
//         size: "5 PCS",
//         price: 2850,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 8,
//     name: "Awesome Fancy Fountains",
//     image: "assets/imgi_52_45.jpg",
//     products: [
//       Product(
//         id: 42,
//         name: "Jolly Ranger",
//         image: "assets/imgi_52_45.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 43,
//         name: "Small Angry Bird Yellow",
//         image: "assets/imgi_53_46.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 44,
//         name: "Small Angry Bird Red",
//         image: "assets/imgi_54_47.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 45,
//         name: "Small Angry Bird Green",
//         image: "assets/imgi_55_48.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 46,
//         name: "Small Angry Bird Silver",
//         image: "assets/imgi_56_49.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 47,
//         name: "Small Angry Bird Red & Green",
//         image: "assets/imgi_57_50.jpg",
//         size: "5 PCS",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 48,
//         name: "Holly Nite",
//         image: "assets/imgi_58_53.jpg",
//         size: "5 PCS",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 49,
//         name: "6000 Crackling",
//         image: "assets/imgi_67_158.jpg",
//         size: "1 PCE",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 9,
//     name: "Awesome Special Fountains",
//     image: "assets/imgi_59_54.jpg",
//     products: [
//       Product(
//         id: 50,
//         name: "Mega Peacock Colour",
//         image: "assets/imgi_59_54.jpg",
//         size: "1 PCE",
//         price: 2100,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 51,
//         name: "Special Bada Peacock Cuckoo",
//         image: "assets/imgi_61_56.jpg",
//         size: "1 PCE",
//         price: 4100,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 52,
//         name: "Bada Peacock Tripple Function",
//         image: "assets/imgi_62_159.jpg",
//         size: "1 PCE",
//         price: 4500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 53,
//         name: "Fountain with Shot Mottu Patlu",
//         image: "assets/imgi_63_57.jpg",
//         size: "1 PCE",
//         price: 2300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 54,
//         name: "Fountain with Shot Jelly & Belly",
//         image: "assets/imgi_66_60.jpg",
//         size: "1 PCE",
//         price: 2300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 55,
//         name: "Fountain with Shot Rock & Pop",
//         image: "assets/imgi_65_59.jpg",
//         size: "1 PCE",
//         price: 2300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 56,
//         name: "Fountain with Shot Fire & Ice",
//         image: "assets/imgi_64_58.jpg",
//         size: "1 PCE",
//         price: 2300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 57,
//         name: "6000 Special Fountain",
//         image: "assets/imgi_67_158.jpg",
//         size: "1 PCE",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 58,
//         name: "Wonder Three",
//         image: "assets/imgi_69_62.jpg",
//         size: "1 PCE",
//         price: 2100,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 59,
//         name: "Siren",
//         image: "assets/imgi_86_63.jpg",
//         size: "3 PCS",
//         price: 1700,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 60,
//         name: "Holly Nite",
//         image: "assets/imgi_58_53.jpg",
//         size: "6 PCS",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 61,
//         name: "Peacock Feather",
//         image: "assets/imgi_68_177.jpg",
//         size: "5 PCS",
//         price: 1300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 62,
//         name: "Nestle",
//         image: "assets/imgi_70_174.jpg",
//         size: "5 PCS",
//         price: 2100,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 10,
//     name: "Dancing and Flying",
//     image: "assets/imgi_72_68.jpg",
//     products: [
//       Product(
//         id: 63,
//         name: "Butterfly",
//         image: "assets/imgi_72_68.jpg",
//         size: "10 PCS",
//         price: 1000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 64,
//         name: "Bambara",
//         image: "assets/imgi_73_69.jpg",
//         size: "10 PCS",
//         price: 1200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 65,
//         name: "Helicopter",
//         image: "assets/imgi_74_70.jpg",
//         size: "5 PCS",
//         price: 1200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 66,
//         name: "Photo Flash",
//         image: "assets/imgi_75_71.jpg",
//         size: "5 PCS",
//         price: 750,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 67,
//         name: "Insta Slfie",
//         image: "assets/imgi_49_44.jpg",
//         size: "3 PCS",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 11,
//     name: "Kids Special",
//     image: "assets/imgi_78_74.jpg",
//     products: [
//       Product(
//         id: 68,
//         name: "Lollipop",
//         image: "assets/imgi_77_73.jpg",
//         size: "5 PCS",
//         price: 2100,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 69,
//         name: "Kit Kat",
//         image: "assets/imgi_78_74.jpg",
//         size: "10 PCS",
//         price: 350,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 70,
//         name: "Money Heist",
//         image: "assets/imgi_79_75.jpg",
//         size: "2 PCS",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 71,
//         name: "Serpent (Pambu Mahtira)",
//         image: "assets/imgi_80_76.jpg",
//         size: "BUNDLE",
//         price: 300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 72,
//         name: "Bada Match Box 5 Star",
//         image: "assets/imgi_83_79.jpg",
//         size: "5 BOXES",
//         price: 1400,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 73,
//         name: "Bada Match Box Laptop",
//         image: "assets/imgi_84_80.jpg",
//         size: "10 BOXES",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 74,
//         name: "Roll Cap",
//         image: "assets/imgi_81_77.jpg",
//         size: "BUNDLE",
//         price: 350,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 75,
//         name: "Ring Cap (Sonny)",
//         image: "assets/imgi_82_78.jpg",
//         size: "POCKET",
//         price: 120,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 76,
//         name: "Cartoon",
//         image: "assets/imgi_32_33.jpg",
//         size: "5 PCS",
//         price: 400,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 12,
//     name: "Rocket",
//     image: "assets/imgi_135_128.jpg",
//     products: [
//       Product(
//         id: 77,
//         name: "Lunic Rocket",
//         image: "assets/imgi_135_128.jpg",
//         size: "10 PCS",
//         price: 1300,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 78,
//         name: "Whistling Rocket",
//         image: "assets/129.jpg",
//         size: "10 PCS",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 13,
//     name: "Sizzling Series",
//     image: "assets/imgi_88_126.jpg",
//     products: [
//       Product(
//         id: 79,
//         name: "Pentagon",
//         image: "assets/imgi_88_126.jpg",
//         size: "5 PCS",
//         price: 1200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 80,
//         name: "White House",
//         image: "assets/imgi_89_127.jpg",
//         size: "5 PCS",
//         price: 1200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 81,
//         name: "Holly Nite",
//         image: "assets/imgi_58_53.jpg",
//         size: "6 PCS",
//         price: 1200,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 14,
//     name: "New Arrivals",
//     image: "assets/imgi_32_33.jpg",
//     products: [
//       Product(
//         id: 82,
//         name: "Lovely Sparklers (Heart Shape)",
//         image: "assets/Lovely-Sparklers-12.jpg",
//         size: "3 PCS",
//         price: 1200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 83,
//         name: "Singing Doll (Whistling Shots)",
//         image: "assets/IMG_20230906_153505-removebg-preview.png",
//         size: "1 PCE",
//         price: 3000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 84,
//         name: "Wire Chakkar",
//         image: "assets/imgi_41_132.jpg",
//         size: "10 PCS",
//         price: 1900,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 85,
//         name: "Hot Wheel",
//         image: "assets/hot-wheels-5pcs-box-.jpg",
//         size: "5 PCS",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 86,
//         name: "Angry Bird Mega",
//         image: "assets/imgi_54_47.jpg",
//         size: "5 PCS",
//         price: 2900,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 87,
//         name: "Rolling Sparklers",
//         image: "assets/roll-cap-box-diwali-fireworks-sale.webp",
//         size: "1 PCE",
//         price: 1900,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 88,
//         name: "Lion Fountain",
//         image: "assets/imgi_32_33.jpg",
//         size: "1 PCE",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 89,
//         name: "Elephant Fountain",
//         image: "assets/imgi_32_33.jpg",
//         size: "1 PCE",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 90,
//         name: "Fire Egg",
//         image: "assets/imgi_76_72.jpg",
//         size: "1 PCE",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 91,
//         name: "Fire & Feather",
//         image: "assets/imgi_32_33.jpg",
//         size: "5 PCS",
//         price: 1400,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 92,
//         name: "Pink Fountain",
//         image: "assets/imgi_32_33.jpg",
//         size: "1 PCE",
//         price: 1800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 93,
//         name: "Violet Sparklers",
//         image: "assets/imgi_32_33.jpg",
//         size: "10 PCS",
//         price: 500,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 15,
//     name: "Continuous Shots",
//     image: "assets/imgi_127_122.jpg",
//     products: [
//       Product(
//         id: 94,
//         name: "12 Shots",
//         image: "assets/imgi_125_117.jpg",
//         size: "1 PCE",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 95,
//         name: "12 Whistling Shots",
//         image: "assets/imgi_32_33.jpg",
//         size: "1 PCE",
//         price: 3000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 96,
//         name: "30 Shots",
//         image: "assets/imgi_127_122.jpg",
//         size: "1 PCE",
//         price: 3800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 97,
//         name: "60 Shots",
//         image: "assets/imgi_128_123.jpg",
//         size: "1 PCE",
//         price: 8000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 98,
//         name: "120 Shots",
//         image: "assets/imgi_129_124.jpg",
//         size: "1 PCE",
//         price: 16000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 99,
//         name: "240 Shots",
//         image: "assets/imgi_130_125.jpg",
//         size: "1 PCE",
//         price: 32000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 100,
//         name: "520 Shots",
//         image: "assets/imgi_131_178.png",
//         size: "1 PCE",
//         price: 80000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 101,
//         name: "10x10",
//         image: "assets/imgi_132_175.png",
//         size: "1 PCE",
//         price: 35000,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 16,
//     name: "Aerial Fancy",
//     image: "assets/imgi_90_81.jpg",
//     products: [
//       Product(
//         id: 104,
//         name: '2" Inch Pipe (3PCS)',
//         image: "assets/imgi_90_81.jpg",
//         size: "3 PCS",
//         price: 2300,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 17,
//     name: '2 1/2" Inch Pipe',
//     image: "assets/imgi_91_82.jpg",
//     products: [
//       Product(
//         id: 105,
//         name: "Egg Change",
//         image: "assets/imgi_91_82.jpg",
//         size: "1 PCE",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 106,
//         name: "Bingo Dance",
//         image: "assets/imgi_92_83.jpg",
//         size: "1 PCE",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 107,
//         name: "Columbus Chio",
//         image: "assets/imgi_93_84.jpg",
//         size: "1 PCE",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 108,
//         name: "Center Point",
//         image: "assets/imgi_94_85.jpg",
//         size: "1 PCE",
//         price: 1700,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 109,
//         name: "Password",
//         image: "assets/imgi_95_86.jpg",
//         size: "1 PCE",
//         price: 1900,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 110,
//         name: "Digital Sound",
//         image: "assets/imgi_96_87.jpg",
//         size: "1 PCE",
//         price: 1500,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 18,
//     name: '3 1/2" Inch Fancy Pipes',
//     image: "assets/imgi_97_88.jpg",
//     products: [
//       Product(
//         id: 111,
//         name: "Mazta",
//         image: "assets/imgi_97_88.jpg",
//         size: "1 PCE",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 112,
//         name: "Red Tails",
//         image: "assets/imgi_98_89.jpg",
//         size: "1 PCE",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 113,
//         name: "Jodi No.1",
//         image: "assets/imgi_99_90.jpg",
//         size: "1 PCE",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 114,
//         name: "Bollywood",
//         image: "assets/imgi_100_91.jpg",
//         size: "1 PCE",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 115,
//         name: "Bluetooth",
//         image: "assets/imgi_101_92.jpg",
//         size: "1 PCE",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 116,
//         name: "Twitter",
//         image: "assets/imgi_102_93.jpg",
//         size: "1 PCE",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//     ],
//   ),

//   ProductCategory(
//     id: 19,
//     name: '4" Inch Fancy Pipes',
//     image: "assets/imgi_103_94.jpg",
//     products: [
//       Product(
//         id: 117,
//         name: "Pinkpearls",
//         image: "assets/imgi_103_94.jpg",
//         size: "1 PCE",
//         price: 3500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 118,
//         name: "Green Shower",
//         image: "assets/imgi_104_95.jpg",
//         size: "1 PCE",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 119,
//         name: "Golden Attack",
//         image: "assets/imgi_105_96.jpg",
//         size: "1 PCE",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 120,
//         name: "Mercury",
//         image: "assets/imgi_106_97.jpg",
//         size: "1 PCE",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 121,
//         name: "Kashmer Chilly",
//         image: "assets/imgi_107_98.jpg",
//         size: "1 PCE",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 122,
//         name: "Silver Line",
//         image: "assets/imgi_108_99.jpg",
//         size: "1 PCE",
//         price: 2800,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 123,
//     name: "4 1/2 Inch Fancy Pipes",
//     image: "assets/imgi_109_100.jpg",
//     products: [
//       Product(
//         id: 123,
//         name: "Navaygra Falls",
//         image: "assets/imgi_110_182.jpg",
//         size: "1 PCE",
//         price: 3200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 124,
//         name: "King Fisher",
//         image: "assets/imgi_112_103.jpg",
//         size: "1 PCE",
//         price: 3200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 125,
//         name: "XXX Seven",
//         image: "assets/imgi_111_102.jpg",
//         size: "1 PCE",
//         price: 3500,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 124,
//     name: "5\" INCH COMBO FANCY PIPES",
//     image: "assets/imgi_119_109.jpg",
//     products: [
//       Product(
//         id: 126,
//         name: "SAMSUNG",
//         image: "assets/imgi_119_109.jpg",
//         size: "2 PCS",
//         price: 9000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 127,
//         name: "NIKON",
//         image: "assets/imgi_120_110.jpg",
//         size: "2 PCS",
//         price: 9000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 128,
//         name: "VIVO",
//         image: "assets/imgi_122_112.png",
//         size: "2 PCS",
//         price: 9000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 129,
//         name: "SONY",
//         image: "assets/imgi_121_111.jpg",
//         size: "2 PCS",
//         price: 9000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 130,
//         name: "AMAZON",
//         image: "assets/imgi_123_113.png",
//         size: "2 PCS",
//         price: 9000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 131,
//         name: "WALMART",
//         image: "assets/imgi_124_114.jpg",
//         size: "2 PCS",
//         price: 9000,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 125,
//     name: "DOUBLE BALL FANCY PIPE",
//     image: "assets/imgi_116_106.jpg",
//     products: [
//       Product(
//         id: 132,
//         name: "SPICEJET (WHITE & RED)",
//         image: "assets/imgi_116_106.jpg",
//         size: "1 PCE",
//         price: 4800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 133,
//         name: "NESTLE (RED & GREEN)",
//         image: "assets/imgi_117_107.jpg",
//         size: "1 PCE",
//         price: 4800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 134,
//         name: "ACTION JACKION (RED & BLUE)",
//         image: "assets/imgi_115_105.jpg",
//         size: "1 PCE",
//         price: 4800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 135,
//         name: "ONCE MORE (YELLOW & GREEN)",
//         image: "assets/imgi_114_104.jpg",
//         size: "1 PCE",
//         price: 4800,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 136,
//         name: "ACTION REPLY (YELLOW & WHITE)",
//         image: "assets/imgi_113_176.jpg",
//         size: "1 PCE",
//         price: 4800,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 126,
//     name: "Sparklers",
//     image: "assets/imgi_144_135.jpg",
//     products: [
//       Product(
//         id: 137,
//         name: "ELECTRIC 10",
//         image: "assets/imgi_144_135.jpg",
//         size: "10 CM",
//         price: 150,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 138,
//         name: "COLOUR CRACKLING 10",
//         image: "assets/imgi_145_136.jpg",
//         size: "10 CM",
//         price: 170,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 139,
//         name: "GREEN 10",
//         image: "assets/imgi_146_137.jpg",
//         size: "10 CM",
//         price: 190,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 140,
//         name: "RED 10",
//         image: "assets/imgi_147_138.jpg",
//         size: "10 CM",
//         price: 200,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 141,
//         name: "ELECTRIC 12",
//         image: "assets/imgi_148_139.jpg",
//         size: "12 CM",
//         price: 210,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 142,
//         name: "COLOUR CRACKLING 12",
//         image: "assets/imgi_149_140.jpg",
//         size: "12 CM",
//         price: 240,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 143,
//         name: "GREEN 12",
//         image: "assets/imgi_150_141.jpg",
//         size: "12 CM",
//         price: 260,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 144,
//         name: "RED 12",
//         image: "assets/imgi_151_142.jpg",
//         size: "12 CM",
//         price: 270,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 145,
//         name: "ELECTRIC 15",
//         image: "assets/imgi_152_143.jpg",
//         size: "15 CM",
//         price: 350,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 146,
//         name: "COLOUR CRACKLING 15",
//         image: "assets/imgi_153_144.jpg",
//         size: "15 CM",
//         price: 370,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 147,
//         name: "GREEN 15",
//         image: "assets/imgi_154_145.jpg",
//         size: "15 CM",
//         price: 390,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 148,
//         name: "RED 15",
//         image: "assets/imgi_155_146.jpg",
//         size: "15 CM",
//         price: 420,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 149,
//         name: "ELECTRIC 30",
//         image: "assets/imgi_156_147.jpg",
//         size: "30 CM",
//         price: 350,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 150,
//         name: "COLOUR CRACKLING 30",
//         image: "assets/imgi_157_148.jpg",
//         size: "30 CM",
//         price: 370,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 151,
//         name: "GREEN 30",
//         image: "assets/imgi_158_149.jpg",
//         size: "30 CM",
//         price: 390,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 152,
//         name: "RED 30",
//         image: "assets/imgi_159_150.jpg",
//         size: "30 CM",
//         price: 420,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 153,
//         name: "ELECTRIC 50",
//         image: "assets/imgi_160_151.jpg",
//         size: "50 CM",
//         price: 1550,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 154,
//         name: "COLOUR CRACKLING 50",
//         image: "assets/imgi_161_152.jpg",
//         size: "50 CM",
//         price: 1700,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 155,
//         name: "ROLLING SPARKLERS",
//         image: "assets/imgi_160_151.jpg",
//         size: "1 PCE",
//         price: 1900,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 127,
//     name: "Candles",
//     image: "assets/imgi_45_41.jpg",
//     products: [
//       Product(
//         id: 156,
//         name: "HITECH PENCIL YELLOW",
//         image: "assets/imgi_45_41.jpg",
//         size: "3 PCS",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 157,
//         name: "HITECH PENCIL SILVER",
//         image: "assets/imgi_46_42.jpg",
//         size: "3 PCS",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 158,
//         name: "HITECH PENCIL RED & GREEN",
//         image: "assets/imgi_47_43.jpg",
//         size: "3 PCS",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 159,
//         name: "SMOKE (DOUBLE EFFECT)",
//         image: "assets/imgi_48_164.jpg",
//         size: "3 PCS",
//         price: 160,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 160,
//         name: "LALA CANDLE",
//         image: "assets/imgi_51_172.jpg",
//         size: "3 PCS",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 161,
//         name: "GOODLY CANDLE",
//         image: "assets/imgi_50_171.jpg",
//         size: "3 PCS",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 162,
//         name: "MINIONS CANDLE",
//         image: "assets/imgi_49_44.jpg",
//         size: "3 PCS",
//         price: 1450,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 128,
//     name: "Gift Boxes",
//     image: "assets/imgi_165_1004.jpg",
//     products: [
//       Product(
//         id: 163,
//         name: "21 items Gift box",
//         image: "assets/imgi_162_1001.jpg",
//         size: "21 items",
//         price: 1750,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 164,
//         name: "30 items Gift box",
//         image: "assets/imgi_163_1002.jpg",
//         size: "30 items",
//         price: 2500,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 165,
//         name: "40 items Gift box",
//         image: "assets/imgi_164_1003.jpg",
//         size: "40 items",
//         price: 4000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 166,
//         name: "50 items Gift box",
//         image: "assets/imgi_165_1004.jpg",
//         size: "50 items",
//         price: 6000,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
//   ProductCategory(
//     id: 129,
//     name: "Awesome Special Package",
//     image: "assets/Screenshot 2025-09-24 182237.png",
//     products: [
//       Product(
//         id: 167,
//         name: "Budget Package",
//         image: "assets/Screenshot 2025-09-24 182200.png",
//         size: "25 shot free",
//         price: 15010,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 168,
//         name: "Family Package (30 shot free)",
//         image: "assets/Screenshot 2025-09-24 182229.png",
//         size: "30 shot free",
//         price: 25000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 169,
//         name: "Premium Package",
//         image: "assets/Screenshot 2025-09-24 182237.png",
//         size: "30 + 25 shot fre",
//         price: 35000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 170,
//         name: "Awesome Package",
//         image: "assets/Screenshot 2025-09-24 182245.png",
//         size: "60 shot free",
//         price: 50000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 171,
//         name: "Awesome Thala Diwali Pack",
//         image: "assets/Screenshot 2025-09-24 182311.png",
//         size: "",
//         price: 40000,
//         unit: "1 BOX",
//       ),
//       Product(
//         id: 172,
//         name: "Awesome Premium Thala Diwali Pack",
//         image: "assets/Screenshot 2025-09-24 182319.png",
//         size: "",
//         price: 16000,
//         unit: "1 BOX",
//       ),
//     ],
//   ),
// ];
